# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a6c2f06b864aed5a20315a4a93b969c4d955461741d69d94cdac0071d6c6e14b6d49b1a3d7c77b09587498148f9c0a5e28417246e248619ba80afe0fedd1e14

test:
  secret_key_base: 927743074f27aa8df04c07f4feb55bb03179edd534e1284b2d8d95f56f4569b9ecb76c427b4e097933e7a845b7d31a85d4a56a2a94203412d8fc875346d42f91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
